config/routes.rb
Rails.application.routes.draw do
  get '/:post_slug/', to: 'posts#show', as: :parent_post
  get '/:post_slug/:subpost_slug', to: 'posts#show', as: :child_post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  scope :published, -> { where(published: true) }
  scope :without_parent, -> { where(parent_slug: nil) }

  has_many :subposts, class_name: 'Post', foreign_key: 'parent_slug', primary_key: 'slug', dependent: :destroy
  belongs_to :parent_post, class_name: 'Post', foreign_key: 'parent_slug', primary_key: 'slug', optional: true
end

app/models/toc.rb
class Toc
  DEFAULT_SECTION = "Without section"
  attr_reader :sections
  attr_reader :posts_by_sections

  def initialize(sections, posts_by_sections)
    @sections, @posts_by_sections = sections, posts_by_sections
  end

  def self.build(post)
    sections = []
    posts_by_sections = Hash.new {|hash, k| hash[k] = []}

    sections << DEFAULT_SECTION

    subposts = post.subposts.published.pluck(:slug, :title).to_h

    current_section = DEFAULT_SECTION
    post.toc_settings["contents"].each do |item|
      if item['type'] == 'section'
        sections << item['name']
        current_section = item['name']
      elsif item['type'] == 'post' && subposts.has_key?(item['slug'])
        posts_by_sections[current_section] << { slug: item['slug'], name: item['name'], parent_slug: post.slug }
        subposts.delete(item['slug'])
      end
    end

    subposts.each do |slug, name|
      posts_by_sections[DEFAULT_SECTION] << { slug: slug, name: name, parent_slug: post.slug }
    end

    new(sections, posts_by_sections)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    post_slug, subpost_slug = params[:post_slug], params[:subpost_slug]

    @post = Post.published.without_parent.find_by_slug!(post_slug)
    @toc = Toc.build(@post)

    if subpost_slug
      @post = @post.subposts.published.find_by_slug!(subpost_slug)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogWithNestedArticles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2>Table of contents</h2>

<ul>
<% @toc.sections.each do |section| %>
  <% if section != Toc::DEFAULT_SECTION  && @toc.posts_by_sections[section].size > 0 %>
    <p><%= section %></p>
  <% end %>
  <ul>
    <% @toc.posts_by_sections[section].each do |item| %>
      <li>
        <%= link_to(item[:name], child_post_path(post_slug: item[:parent_slug], subpost_slug: item[:slug])) %>
      </li>
    <% end %>
  </ul>
<% end %>
</ul>

<h2>Content</h2>
<p><%= @post.content %></p>

<% if @post.parent_slug %>
  <p><%= link_to("Return to parent", parent_post_path(post_slug: @post.parent_slug)) %></p>
<% end %>